### ISSUE TITLE
Add better support for non-HCL output files

### ISSUE THREAD

**Issue by aurynn** [verifa/terraplate#16]
I'm looking at using Terraplate for my projects, and I'm having issues with generating non-HCL outputs correctly.

In my case, I'm generating a YAML file that has `${{somevalue}}` literal strings in it, and wrapping the value in `{{ "${{somevalue}}"}}` to have a string literal in the Go template still produces `$ { { somevalue } }`, which is not what I want.

**Comment by jlarfors** [comment]
@aurynn thanks for trying terraplate and sorry for the late reply (notifications enabled now).

Terraplate uses the Go templating engine and your syntax does not look correct. It should instead be something like: `{{ .somevalue }}`.

However there was an issue that ALL files were being formatted as HCL files. I implemented a simple fix to only format `.tf` files, and this means you can now template YAML files.

I added an example for you here: https://github.com/verifa/terraplate/tree/main/examples/yaml/templates

**Comment by aurynn** [comment]
Wonderful, thank you! 😄
